package com.txcjh.fazhanceping.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.video_path
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    private String videoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_excelent
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    private Boolean isExcelent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.score
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public UserInfo(Integer userId, String userName, String videoPath, Boolean isExcelent, Integer score) {
        this.userId = userId;
        this.userName = userName;
        this.videoPath = videoPath;
        this.isExcelent = isExcelent;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.video_path
     *
     * @return the value of user_info.video_path
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.video_path
     *
     * @param videoPath the value for user_info.video_path
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_excelent
     *
     * @return the value of user_info.is_excelent
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public Boolean getIsExcelent() {
        return isExcelent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_excelent
     *
     * @param isExcelent the value for user_info.is_excelent
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public void setIsExcelent(Boolean isExcelent) {
        this.isExcelent = isExcelent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.score
     *
     * @return the value of user_info.score
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.score
     *
     * @param score the value for user_info.score
     *
     * @mbggenerated Wed Feb 27 14:17:47 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}