package com.txcjh.fazhanceping.model;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.passwd
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public Users(Integer userId, String passwd) {
        this.userId = userId;
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public Users() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.passwd
     *
     * @return the value of users.passwd
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.passwd
     *
     * @param passwd the value for users.passwd
     *
     * @mbggenerated Wed Feb 27 15:49:52 CST 2019
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}