package com.txcjh.fazhanceping.mapper;

import com.txcjh.fazhanceping.model.Tuiyou;
import com.txcjh.fazhanceping.model.TuiyouExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TuiyouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int countByExample(TuiyouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int deleteByExample(TuiyouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int insert(Tuiyou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int insertSelective(Tuiyou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    List<Tuiyou> selectByExample(TuiyouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tuiyou record, @Param("example") TuiyouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuiyou
     *
     * @mbggenerated Wed Feb 27 17:53:12 CST 2019
     */
    int updateByExample(@Param("record") Tuiyou record, @Param("example") TuiyouExample example);

    List<Integer> getByKeyAndObject(Integer userId);
}